export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
          <p>HEADER</p>
        </header>
        {children}
        <footer
          style={{ backgroundColor: "black", padding: "1rem", color: "white" }}
        >
          <p>FOOTER</p>
        </footer>
      </body>
    </html>
  );
}
